version: '3.8'

services:
  postgres:
    container_name: postgres
    command: ['postgres', '-c', 'log_statement=all']
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
